fix(react): forceRender fix
artalar/reatom pull request #345
Opened 2020-06-26 13:07 UTC by nickshevr

2020-06-26 13:41 UTC, artalar requested changes

2020-06-26 13:41 UTC, artalar commented on packages/react/src/index.ts
> +  return useReducer<Reducer<boolean, null>>(s => s++, true)[1] as () => void
```suggestion
  return useReducer<Reducer<boolean, null>>(s => s++, 0)[1] as () => void
```

2020-06-26 13:43 UTC, nickshevr commented on packages/react/src/index.ts
> +  return useReducer<Reducer<boolean, null>>(s => s++, true)[1] as () => void
Надо еще не от `boolean`, мб лучше `Date.now()` вообще?

2020-07-03 16:51 UTC, artalar approved these changes

2020-07-03 16:51 UTC, merged

2020-07-03 19:18 UTC, arswarog commented on packages/react/src/index.ts
> +  return useReducer<Reducer<boolean, null>>(s => s++, true)[1] as () => void
только не `s => s++` а `s => ++s `или `s => s + 1` постфиксный инкремент не прокатит