add new primitive atomizeArray
artalar/reatom pull request #419
Opened 2022-07-03 20:56 UTC by aleksandrtamrazov

add new primitive atomizeArray following the example of atomizeSet, there is a question about duplicates in state and method filter, do not pour in until we discuss @artalar.

2022-07-04 09:16 UTC, artalar commented
Please, implement this type

```ts
export type ArrayAtom<T> = WithReducers<
  AtomMut<Array<T>>,
  {
    add(state: Array<T>, value: T): Array<T>
    remove(
      state: Array<T>,
      from: number,
      to?: number /* = from + 1 */,
    ): Array<T>
    replace(
      state: Array<T>,
      newStatePart: Array<T>,
      from?: number /* = 0 */,
      to?: number /* = this.length - 1 */,
    ): Array<T>
    clear(): Array<T>
    reset(): Array<T>
  }
>```

2022-07-04 09:30 UTC, artalar commented
btw, all kind of transformations could be described by `flatMap` (and `[...state, added]`):

```ts
// remove from a middle
listAtom(ctx, state => state.flatMap((v) => (v === 2 ? [] : v)))
// [1, 3]

// add to a middle
listAtom(ctx, state => state.flatMap((v) => (v === 2 ? [2, 2.5] : v)))
// [1, 2, 2.5, 3]
```

do we really need extra methods? 🤔

2022-07-07 18:55 UTC, altamraz commented
@artalar, The problem is that I don't get how write tests for atomizeArray. Please, describe one case for example method `add` for me in this conversation. The following tests I will describe myself.

2022-07-07 19:52 UTC, artalar commented
Hi! I was thinking about all of it and propose a small changes:

```ts
export type ArrayAtom<T> = WithReducers<
  AtomMut<Array<T>>,
  {
    put(
      state: Array<T>,
      value: T,
      position?:
        | number
        | ((el: T, index: number) => boolean) /* = this.length */
    ): Array<T>;
    remove(
      state: Array<T>,
      from: number,
      to?: number /* = from */
    ): Array<T>;
    replace(
      state: Array<T>,
      newStatePart: Array<T>,
      from?: number /* = 0 */,
      to?: number /* = this.length - 1 */
    ): Array<T>;
    clear(): Array<T>;
    reset(): Array<T>;
  }
>;

// EXAMPLES

atomizeArray([1, 2, 3]).put(ctx, 4)
// [1, 2, 3, 4]

atomizeArray([1, 2, 3]).put(ctx, 4, 0)
// [4, 2, 3]

atomizeArray([1, 2, 3]).put(ctx, 4, (el) => el === 2)
// [1, 4, 3]
```

2022-07-12 10:43 UTC, artalar commented
@altamraz please, change `to` to `count` and allow callback for `from`:

> In this case `remove` will super simple: `(state, from, count = 1) => replace(state, [], from, count)`

```ts
export type ArrayAtom<T> = WithReducers<
  AtomMut<Array<T>>,
  {
    put(
      state: Array<T>,
      value: T,
      position?:
        | number
        | ((el: T, index: number) => boolean) /* = this.length */
    ): Array<T>;
    remove(
      state: Array<T>,
      from: number | ((el: T, index: number) => boolean),
      count?: number /* = 1 */
    ): Array<T>;
    replace(
      state: Array<T>,
      newStatePart: Array<T>,
      from?: number | ((el: T, index: number) => boolean) /* = 0 */,
      count?: number /* = this.length - from */
    ): Array<T>;
    clear(): Array<T>;
    reset(): Array<T>;
  }
>;
```

2022-07-13 07:28 UTC, altamraz commented
Add new Type ArrayAtom
```
export type ArrayAtom<T> = WithReducers<
  AtomMut<Array<T>>,
  {
    toReversed(): Array<T>
    toSorted(compareFn?: (a: T, b: T) => number): Array<T>
    toSpliced(state: Array<T>, start: number, deleteCount: number, ...items: T[]): Array<T>
    with(state: Array<T>, index: number, value: T): Array<T>
  }
>
```

2022-07-13 13:08 UTC, artalar commented on packages/primitives/src/atomizeArray.ts
> +      },
```suggestion
      toReversed: (state) => state.slice(0).reverse(),
      toSorted: (state, compareFn) => state.slice(0).sort(compareFn),
```

2022-07-13 13:08 UTC, artalar requested changes

2022-07-13 13:08 UTC, artalar commented on packages/primitives/src/atomizeArray.ts
> +        const newState = state.slice(0)
reuse `state` variable

2022-07-13 13:08 UTC, artalar commented on packages/primitives/src/atomizeArray.ts
> +        const newState = state.slice(0)
reuse `state` variable

2022-07-13 14:26 UTC, artalar approved these changes

2022-07-13 14:27 UTC, merged