refactor: replace 'Fn' type with function type expression (closes #565)
artalar/reatom pull request #566
Opened 2023-05-07 15:32 UTC by alexvyber

2023-05-09 04:40 UTC, artalar commented
Hi! Thank you for this, it is a lot of work, I appreciate it! I need a few days to review the changes and add some suggestions around arguments namenes.

2023-05-11 04:32 UTC, artalar requested changes

2023-05-11 04:32 UTC, artalar commented on docs/src/pages/guides/custom-operator.md
> +  mapper: (ctx: CtxSpy, arg1: T,  arg2: undefined | T) => Res,
```suggestion
  mapper: (ctx: CtxSpy, state: T,  prevState: undefined | T) => Res,
```

2023-05-11 04:32 UTC, artalar commented on docs/src/pages/packages/testing.md
> +  subscribeTrack<T, F extends (arg: T) => any>(
```suggestion
  subscribeTrack<T, F extends (state: T) => any>(
```

2023-05-11 04:32 UTC, artalar commented on packages/async/src/index.ts
> +  onReject?: (ctx: Ctx, arg: unknown) => any
```suggestion
  onReject?: (ctx: Ctx, error: unknown) => any
```

2023-05-11 04:32 UTC, artalar commented on packages/async/src/index.ts
> +    arg: T,
```suggestion
    anAsync: T,
```

2023-05-11 04:32 UTC, artalar commented on packages/async/src/index.ts
> +  ): (arg: T) => T & { dataAtom: AsyncDataAtom<ActionPayload<T['onFulfill']>> }
```suggestion
  ): (anAsync: T) => T & { dataAtom: AsyncDataAtom<ActionPayload<T['onFulfill']>> }
```

2023-05-11 04:32 UTC, artalar commented on packages/async/src/index.ts
> +    arg: T,
```suggestion
    anAsync: T,
```

2023-05-11 04:32 UTC, artalar commented on packages/async/src/index.ts
> +  ): (arg: T) => T & { dataAtom: AsyncDataAtom<ActionPayload<T['onFulfill']>> }
```suggestion
  ): (anAsync: T) => T & { dataAtom: AsyncDataAtom<ActionPayload<T['onFulfill']>> }
```

2023-05-11 04:32 UTC, artalar commented on packages/async/src/index.ts
> +  ): (arg: T) => T & { dataAtom: AsyncDataAtom<State> }
```suggestion
  ): (anAsync: T) => T & { dataAtom: AsyncDataAtom<State> }
```

2023-05-11 04:32 UTC, artalar commented on packages/async/src/index.ts
> +    parseError: (ctx: Ctx, arg: unknown) => Err = (ctx, e) =>
```suggestion
    parseError: (ctx: Ctx, error: unknown) => Err = (ctx, e) =>
```

2023-05-11 04:32 UTC, artalar commented on packages/async/src/index.ts
> +    arg: T,
```suggestion
    anAsync: T,
```

2023-05-11 04:32 UTC, artalar commented on packages/async/src/index.ts
> +  }: { strategy?: 'none' | 'last-in-win' } = {}): ((arg: T) => T & {
```suggestion
  }: { strategy?: 'none' | 'last-in-win' } = {}): ((anAsync: T) => T & {
```

2023-05-11 04:32 UTC, artalar commented on packages/async/src/withCache.ts
> +        arg: any[],
```suggestion
        params: any[],
```

2023-05-11 04:35 UTC, artalar commented
@alexvyber please, merge the fresh changes from `v3`

2023-06-07 04:38 UTC, artalar commented
@alexvyber could you merge from v3 one more time please?) I plan to publish the changes today

2023-06-11 09:08 UTC, alexvyber commented
> @alexvyber could you merge from v3 one more time please?) I plan to publish the changes today

Whoops...
Sorry, I just this comment.
Today will do it.

2023-06-11 13:02 UTC, artalar commented
Thank you :)

2023-06-12 05:12 UTC, artalar approved these changes

2023-06-12 05:12 UTC, merged