ew documentation structure
artalar/reatom pull request #621
Opened 2023-09-03 19:53 UTC by Akiyamka

2023-10-23 21:38 UTC, artalar requested changes

2023-10-23 21:38 UTC, artalar commented on docs/src/content/docs/getting-started/try-online.md
> +
```suggestion
Here is the base template project with Vite, TypeScript, React and Reatom ecosystem: https://github.com/artalar/reatom-react-ts

Try it online: [codesandbox](https://codesandbox.io/p/sandbox/github/artalar/reatom-react-ts/tree/main), [stackblitz](https://githubblitz.com/artalar/reatom-react-ts), [gitpod](https://gitpod.io/#https://github.com/artalar/reatom-react-ts)

```

2023-10-23 21:38 UTC, artalar commented on docs/src/content/docs/getting-started/setup.md
> +
```suggestion

Reatom is a framework-agnostic state manager, and you can use it with various adapters for different frameworks. This guide provides a common usage with React.js, as it is the most commonly used view library currently.

```

2023-10-23 21:38 UTC, artalar commented on docs/src/content/docs/getting-started/setup.md
> +### With ESlint
MOVE IT TO SEPARATE GUIDLE PLEASE. Let's not add extra complexity for newbie right from the first steps.

2023-10-23 21:38 UTC, artalar commented on docs/src/content/docs/getting-started/setup.md
> +React 16 and 17:
Definitely, there is excessive information. We should only focus on the main flow.

2023-10-23 21:38 UTC, artalar commented on docs/src/content/docs/getting-started/setup.md
> +For `react-native`:
There's no need for it there too.

2023-10-23 21:38 UTC, artalar commented on docs/src/content/docs/getting-started/setup.md
> +  const [name] = useAtom(nameAtom)
may be we will use `setName` here and don't mention `action` at all?

- less complexity
- `useAtom` will be more familiar and understandable with the setter, just like `useState`

2023-10-23 21:38 UTC, artalar commented on docs/src/content/docs/getting-started/learning.md
> +const ctx = createCtx()
Move `ctx` creation bellow. It is important to focus on the context last of all. Add extra comment that `ctx` created only once.

2023-10-23 21:38 UTC, artalar commented on docs/src/content/docs/getting-started/learning.md
> +})
Computation in the `subscribe` function is what you should avoid initially. It should serve as a bridge for side effects only.

2023-10-23 21:38 UTC, artalar commented on docs/src/content/docs/getting-started/learning.md
> +// logs: 3, 4, 7
```suggestion
aAtom(ctx, 3)
// logs: 3 + 2 = 5

bAtom(ctx, 4)
// logs: 3 + 4 = 7

bAtom(ctx, 4)
// does not log anything, as the state is not changed

console.log(ctx.get(aAtom), ctx.get(bAtom), ctx.get(cAtom))
// logs: 3, 4, 7
```

2023-10-23 21:38 UTC, artalar commented on docs/src/content/docs/getting-started/learning.md
> +2. Computed atoms should be pure functions. You can't know how many times they will be called. But reatom will try to keep call count as small as possible.
```suggestion
2. Computed atoms should be pure functions to archive the correct order of all computations
```

2023-10-23 21:38 UTC, artalar commented on docs/src/content/docs/getting-started/learning.md
> +const accAtom = atom<number>((ctx, prev = 0) => prev + 1, 'accAtom')
Very weird example :)
```suggestion
import { atom, isDeepEqual } from '@reatom/framework'

const listAtom = atom<List>([], 'listAtom')
const filteredListAtom = atom((ctx, state = []) => {
  const newState = ctx.spy(listAtom).filter(predicate)
  return isDeepEqual(state, newState) ? state : newState
}, 'filteredListAtom')
```

2023-10-23 21:38 UTC, artalar commented on docs/src/content/docs/getting-started/learning.md
> +```
```suggestion
```

To fix this, simply wrap the value in atom and spy, and change it within the relative context.
```

2023-10-23 21:38 UTC, artalar commented on docs/src/content/docs/getting-started/debugging.md
> +
```suggestion
<!-- TODO add `anAtom.onChange(console.log)` docs above -->
```

2023-10-23 21:38 UTC, artalar commented on docs/src/content/docs/getting-started/debugging.md
> +---
Please, fill this page with the original content (https://reatom-git-structured-docs-artalar.vercel.app/getting-started/debugging/) or mix it together

2023-10-23 21:38 UTC, artalar commented on docs/astro.config.mjs
> +          label: 'Recipes',
Please, hide this whole section from the sidebar, as it not ready yet.

2023-10-30 20:11 UTC, Akiyamka commented on docs/src/content/docs/getting-started/try-online.md
> +
How to install locally described with details in setup section

2023-10-31 23:00 UTC, artalar submitted a review, later dismissed

2023-10-31 23:04 UTC, merged