feat(persist-web-storage): add withCookie
artalar/reatom pull request #830
Opened 2024-04-29 21:05 UTC by Laniman

Solve #825

2024-04-30 05:07 UTC, artalar requested changes

2024-04-30 05:07 UTC, artalar commented on packages/persist-web-storage/src/reatomPersistCookie.ts
> +        if (!dataStr) return null
Move it inside the `try`

2024-04-30 05:07 UTC, artalar commented on packages/persist-web-storage/src/reatomPersistCookie.ts
> +          document.cookie = `${key}=${JSON.stringify(rec)}${stringifyAttrs(
Use `encodeURIComponent`

2024-05-01 12:54 UTC, Laniman commented on packages/persist-web-storage/src/reatomPersistCookie.ts
> +          document.cookie = `${key}=${JSON.stringify(rec)}${stringifyAttrs(
fixed

2024-05-01 12:54 UTC, Laniman commented on packages/persist-web-storage/src/reatomPersistCookie.ts
> +        if (!dataStr) return null
fixed

2024-05-01 13:10 UTC, artalar approved these changes

2024-05-01 13:22 UTC, merged