feat(jsx): normalize class attribute
artalar/reatom pull request #942
Opened 2024-10-14 14:58 UTC by kasperskei

Class binding like [vue.js](https://vuejs.org/guide/essentials/class-and-style.html#binding-html-classes).

2024-10-15 07:41 UTC, kasperskei commented on packages/jsx/src/index.test.tsx
> +  assert.is(((<Component draggable="true" />) as HTMLElement).draggable, true)
Attribute is not boolean
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/draggable

2024-10-22 12:10 UTC, artalar commented on packages/jsx/src/index.ts
> +      } else if (k === 'class' && containsAtom(prop)) {
```suggestion
      } else if ((isAtom(prop) && !prop.__reatom.isAction) || ((k === 'class' || k === 'className') && isObject(prop) && (isAtom(prop) || (prop = reatomClassName(prop))))) {
```

Also

```ts
const reatomClassName = (value: object) =>
  atom((ctx, state = '') => {
    if (state && ctx.cause.pubs.length === 0) {
      ctx.cause.proto.computer = null
    } else {
      state = ''
      for (const name in value) {
        if (isAtom(value[name]) ? ctx.spy(value[name]) : value[name]) state += name + ' '
      }
    }

    return state
  })
```

2024-10-23 10:42 UTC, Akiyamka commented on packages/jsx/src/utils.test.ts
> +      [],
It's a bit inconsistent, that we treat `{}` and `[]`   
In js world they truly, and in test above ('handles falsy object correctly') we not test it ether

2024-10-23 10:44 UTC, Akiyamka commented on packages/jsx/src/utils.test.ts
> +    assert.is(ctx.get(cn(['a', ['b', ['c']]])), 'a b c   ')
this extra spaces at the end - interned behavior?

2024-10-23 10:47 UTC, Akiyamka commented on packages/jsx/src/utils.ts
> +        className += normalized + ' '
```suggestion
        className += normalized ? normalized + ' ' : normalized
```

2024-10-23 10:48 UTC, Akiyamka commented on packages/jsx/src/utils.ts
> +        className += normalized + ' '
Should fix extra spaces

2024-10-23 19:14 UTC, artalar commented on packages/jsx/src/utils.test.ts
> +    assert.is(ctx.get(cn(['a', ['b', ['c']]])), 'a b c   ')
Yep, it our optimization to not trying to trim each string

2024-10-23 19:26 UTC, artalar requested changes

2024-10-23 19:26 UTC, artalar commented on packages/jsx/src/index.ts
> -    } else if (key === 'style' && typeof val === 'object') {
Wow, why you removed the style props handling? Please, restore it and add additional tests for css vars, which will ensure that we will not remove this feature again later :)

2024-10-23 19:26 UTC, artalar commented on packages/jsx/src/utils.ts
> +const reatomClassName = (ctx: CtxSpy, value: ClassValue): string => {
A thing name starts with "reatom*" if it returns an atom or an action. Name it `parseClasses`, maube, or something like that

2024-10-23 19:26 UTC, artalar commented on packages/jsx/src/utils.test.ts
> +})
Please, test the change behaviour of created atom to ensure that the created atom correctly subscribes (spy) to nested atom. You can change one of the existing tests

2024-10-23 19:26 UTC, artalar commented on packages/jsx/src/utils.ts
> +type ClassValue = AtomMaybe<
```suggestion
export type ClassNameValue = AtomMaybe<
```

2024-10-23 19:26 UTC, artalar commented on packages/jsx/src/utils.ts
> +    for (let i = 0; i < length; i++) {
```suggestion
    for (let i = 0; i < value.length; i++) {
```

2024-10-23 19:26 UTC, artalar commented on packages/jsx/src/utils.ts
> +      if (normalized) {
Always use strict comparison in this kind utilities to improve performance
```suggestion
      if (normalized !== '') {
```

2024-10-24 08:38 UTC, artalar commented on packages/jsx/src/index.ts
> +        if (key === 'class' && element instanceof HTMLElement) element.className = val
Should we handle className too? Btw, don't forget to change the types
```suggestion
        if ((key === 'class' || key === 'className') && element instanceof HTMLElement) element.className = val
```

2024-10-24 09:14 UTC, artalar approved these changes

2024-10-31 23:23 UTC, merged