fix(url): add subpath parameter
artalar/reatom pull request #945
Opened 2024-10-22 13:16 UTC by caio2983

#880 

Hello @artalar ,
I tried tackling on this issue, but I'm not sure if I managed to solve it . The current test in the url package 'SearchParamsAtom.lens' couldn't pass . I got the behavior below :  ( by adding subpath: () => '/results' parameter to withSearchParamsPersist options object ) 

![ezgif-2-6e00733331](https://github.com/user-attachments/assets/384dbc32-5716-49db-a832-92b5b7912de0)

As you can see , the subpath '' results '' persists while the '' page '' parameter changes 

As I said , I don't know if I solved the issue partially , but perhaps you can find something of value in the changes I made

2024-10-25 08:44 UTC, artalar commented
@caio2983 hi! This is awesome, thnaks for your contributing! I will review it today a little bit later

2024-10-31 23:34 UTC, artalar requested changes
Please, add tests

2024-10-31 23:34 UTC, artalar commented on packages/url/src/index.ts
> +        // Atualiza o estado apenas se o caminho estiver no subpath permitido
Use en comments, please

2024-10-31 23:34 UTC, artalar commented on packages/url/src/index.ts
> +        const { pubs } = ctx.cause;
Remove all unnexesary brakets. You can use our prettier config

2024-11-01 19:39 UTC, caio2983 commented
> Please, add tests

Understood, I will work on those tests and soon come up with updates

2024-11-01 19:40 UTC, caio2983 commented on packages/url/src/index.ts
> +        // Atualiza o estado apenas se o caminho estiver no subpath permitido
I apologize for that. I forgot to remove those comments

2024-11-05 10:53 UTC, artalar approved these changes

2024-11-05 10:53 UTC, merged

2024-11-05 10:54 UTC, artalar commented
Thanks!