chore: migrate to vitest
artalar/reatom pull request #948
Opened 2024-10-27 05:01 UTC by caio2983

#947 

Hello @artalar ,
Please let me know if any changes need to be done in this

2024-10-28 11:34 UTC, artalar requested changes
Huge work, thank you! Please, follow the comments and be ready that today I will publish a couple updates and refactoring INCLUDING the async package migration to the vitest, to there will be a small merge conflicts

2024-10-28 11:34 UTC, artalar commented on packages/async/src/index.story.test.ts
> +    Also, we use onConnect to fetch the list from the server every 5 seconds
Why the quotes removed?

2024-10-28 11:34 UTC, artalar commented on packages/async/src/index.story.test.ts
> -    // add `dataAtom` and map the effect payload into it
Why the comments removed?

2024-10-28 11:34 UTC, artalar commented on packages/async/src/mapToAsync.test.ts
> -export const test = suite('mapToAsync')
There is no need to use `describe`, please change the tests runner script to this:

```json
    "test": "vitest run src/*.test.ts",
    "test:watch": "vitest src/*.test.ts"
```

2024-10-28 15:53 UTC, caio2983 commented
> Huge work, thank you! Please, follow the comments and be ready that today I will publish a couple updates and refactoring INCLUDING the async package migration to the vitest, to there will be a small merge conflicts

Understood, I just removed that one describe usage , changed the tests runner script and fixed the comments . 

Should I change the tests runner scripts to     "test": "vitest run src/*.test.ts",
    "test:watch": "vitest src/*.test.ts" in every package besides async?

2024-11-01 00:12 UTC, artalar commented
@caio2983 ive updated the deps and the async package tests, please check

> Should I change the tests runner scripts to "test": "vitest run src/.test.ts",
"test:watch": "vitest src/.test.ts" in every package besides async?
yep

2025-01-18 21:20 UTC, artalar commented
@caio2983 Hi! Sorry for the delay, I have been super busy, working, sick and many other bus factor things :) Are you interested in continuing to work on this PR? I would love to merge it as soon as possible.

2025-01-20 21:02 UTC, AgarkovRoman commented on packages/async/src/index.story.test.ts
> +import { describe, it, expect } from 'vitest'
btw, you can set up a `global: true` in vitest.config and this will allow you to remove all imports from 'vitest'

https://vitest.dev/config/#globals

2025-01-20 21:05 UTC, AgarkovRoman commented
consider to use a [workspace feature](https://vitest.dev/guide/workspace.html#workspace) in vitest which can be useful for monorepo such as reatom

2025-01-22 09:03 UTC, artalar commented on packages/async/src/index.story.test.ts
> +import { describe, it, expect } from 'vitest'
imho direct import is more obvious.

2025-01-22 18:41 UTC, AgarkovRoman commented
@artalar I can take over this and continue migration, do you mind?

2025-01-24 08:33 UTC, artalar commented
@AgarkovRoman ok, go ahead.

2025-03-10 08:43 UTC, artalar commented
done in #1026

2025-03-10 08:43 UTC, closed without merging